# Generated by Django 3.2.6 on 2021-08-25 13:27

import app.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4096, verbose_name='Cообщение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/broadcast-all/%Y_%m_%d/', verbose_name='Фото')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
            ],
            options={
                'verbose_name': 'общую рассылку',
                'verbose_name_plural': 'Общие рассылки',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название портфеля')),
                ('users_list', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('users_count', models.IntegerField(default=0, verbose_name='Количество подписанных')),
            ],
            options={
                'verbose_name': 'портфель',
                'verbose_name_plural': ' Портфели',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.CharField(default=app.models.get_code, max_length=6, unique=True, verbose_name='Промокод')),
                ('valid_date', models.DateField(default=app.models.add_one_year, verbose_name='Действителен до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': ' Промокоды',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, verbose_name='Ccылка')),
            ],
            options={
                'verbose_name': 'видеоурок',
                'verbose_name_plural': '  Видеоуроки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('subscription_status', models.BooleanField(default=False, verbose_name='Статус подписки')),
                ('subscribed_until', models.DateField(null=True, verbose_name='Подписка до')),
                ('number_of_subscriptions', models.PositiveSmallIntegerField(default=0)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], default=None, max_length=2, null=True, verbose_name='Язык')),
                ('date_joined', models.DateField(auto_now_add=True, null=True, verbose_name='Дата присоединения')),
                ('portfolio', models.ManyToManyField(to='app.Portfolio', verbose_name='Портфели пользователя')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': '   Пользователи',
            },
        ),
        migrations.CreateModel(
            name='BroadcastSelective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4096, verbose_name='Cообщение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/broadcast-selective/%Y_%m_%d/', verbose_name='Фото')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'выборочную рассылку',
                'verbose_name_plural': 'Выборочные рассылки',
            },
        ),
    ]
