# Generated by Django 3.2.6 on 2021-08-25 15:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_promo_valid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=app.models.add_one_year, verbose_name='Действителен до'),
        ),
    ]
