# Generated by Django 3.2.6 on 2021-08-27 09:11

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_promo_valid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastselective',
            name='style_text',
            field=markdownfield.models.RenderedMarkdownField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadcastselective',
            name='text',
            field=markdownfield.models.MarkdownField(default=None, rendered_field='style_text'),
            preserve_default=False,
        ),
    ]
