# Generated by Django 3.2.6 on 2021-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210813_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.CharField(blank=True, default='9hc9rifvGkiSg43W9plZmm454zgbcq90', editable=False, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
