# Generated by Django 3.2.6 on 2021-08-27 09:13

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210827_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastselective',
            name='text',
            field=markdownfield.models.MarkdownField(default='-', rendered_field='style_text'),
        ),
    ]
