# Generated by Django 3.2.6 on 2021-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='valid_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='FKih3ai86qNJQJLkvz5us46CCuyRQK3i', editable=False, max_length=255, null=True, unique=True),
        ),
    ]
