# Generated by Django 3.2.6 on 2021-08-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_broadcastselective_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastselective',
            name='style_text',
        ),
        migrations.RemoveField(
            model_name='broadcastselective',
            name='text',
        ),
    ]
