# Generated by Django 3.2.6 on 2021-08-27 09:16

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210827_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastselective',
            name='style_text',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='broadcastselective',
            name='text',
            field=markdownfield.models.MarkdownField(default='-', rendered_field='style_text'),
        ),
    ]
