# Generated by Django 3.2.6 on 2021-08-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210827_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastselective',
            name='style_text',
        ),
        migrations.RemoveField(
            model_name='broadcastselective',
            name='text',
        ),
    ]
