# Generated by Django 3.2.6 on 2021-08-13 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_promo_promo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='BZRCJG', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='used',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 19, 28, 34, 657214)),
        ),
    ]
