# Generated by Django 3.2.6 on 2021-08-13 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210813_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='used',
            new_name='is_used',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='0C80DK', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 13, 20, 48, 6, 862980)),
        ),
    ]
