# Generated by Django 3.2.6 on 2021-08-14 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210813_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='ARPL4B', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 12, 52, 43, 306229)),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default=None, editable=False, max_length=2, null=True),
        ),
    ]
