# Generated by Django 3.2.6 on 2021-08-14 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210814_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='LHBKKJ', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 17, 4, 46, 895837)),
        ),
    ]
