# Generated by Django 3.2.6 on 2021-08-14 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210814_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфель', 'verbose_name_plural': 'Портфели'},
        ),
        migrations.AlterField(
            model_name='promo',
            name='is_used',
            field=models.BooleanField(default=False, editable=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='U1YRG3', max_length=255, null=True, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 19, 3, 42, 617430), verbose_name='Действителен до'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.ManyToManyField(to='app.Portfolio'),
        ),
    ]
