# Generated by Django 3.2.6 on 2021-08-15 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210814_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='is_used',
        ),
        migrations.AddField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='H286K5', max_length=255, null=True, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 15, 15, 21, 15, 27574), verbose_name='Действителен до'),
        ),
    ]
