# Generated by Django 3.2.6 on 2021-08-16 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210815_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название портфеля'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='ZUKL5W', max_length=255, null=True, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 10, 50, 22, 374355), verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='portfolio',
            field=models.ManyToManyField(to='app.Portfolio', verbose_name='Портфели пользователя'),
        ),
    ]
