# Generated by Django 3.2.6 on 2021-08-16 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210816_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='BHX51N', max_length=255, null=True, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 11, 7, 57, 488697), verbose_name='Действителен до'),
        ),
    ]
