# Generated by Django 3.2.6 on 2021-08-16 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210816_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user_list',
            field=models.TextField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='C2ZT70', max_length=255, null=True, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 12, 32, 45, 266042), verbose_name='Действителен до'),
        ),
    ]
