# Generated by Django 3.2.6 on 2021-08-16 07:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210816_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_valid',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Действителен до'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(blank=True, default='6QUK5N', max_length=255, null=True, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 12, 40, 17, 572000), verbose_name='Действителен до'),
        ),
    ]
