# Generated by Django 3.2.6 on 2021-08-16 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210816_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='user_list',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(default='EYK0Q0', max_length=255, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 14, 15, 28, 890478), verbose_name='Действителен до'),
        ),
    ]
