# Generated by Django 3.2.6 on 2021-08-16 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210816_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(default='P6Z02M', max_length=255, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 18, 41, 35, 556698), verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_valid',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 41, 35, 556698), verbose_name='Подписка до'),
        ),
    ]
