# Generated by Django 3.2.6 on 2021-08-16 15:19

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210816_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, default=None, null=True), default=None, size=None),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(default='HF05VM', max_length=255, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 20, 19, 2, 446049), verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_valid',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 20, 19, 2, 444767), verbose_name='Подписка до'),
        ),
    ]
