# Generated by Django 3.2.6 on 2021-08-17 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210816_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписка до'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(default='QGVBU1', max_length=255, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 17, 11, 9, 7, 937217), verbose_name='Действителен до'),
        ),
    ]
