# Generated by Django 3.2.6 on 2021-08-17 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210817_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_subscriptions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(default='VC47UL', max_length=255, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 17, 11, 11, 46, 642698), verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_until',
            field=models.DateTimeField(null=True, verbose_name='Подписка до'),
        ),
    ]
