# Generated by Django 3.2.6 on 2021-08-17 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210817_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(default='CISZAG', max_length=255, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 17, 11, 22, 1, 589801), verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_until',
            field=models.DateField(null=True, verbose_name='Подписка до'),
        ),
    ]
