# Generated by Django 3.2.6 on 2021-08-18 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210817_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videolesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='Ccылка')),
            ],
            options={
                'verbose_name': 'Видеоурок',
                'verbose_name_plural': 'Видеоуроки',
            },
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 11, 21, 32, 375901), verbose_name='Действителен до'),
        ),
    ]
