# Generated by Django 3.2.6 on 2021-08-18 06:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210818_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='valid_date',
            field=models.DateField(default=app.models.add_one_year, verbose_name='Действителен до'),
        ),
    ]
