# Generated by Django 3.2.6 on 2021-08-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_promo_valid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
