# Generated by Django 3.2.6 on 2021-08-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_videolesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
