# Generated by Django 3.2.6 on 2021-08-18 11:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_videolesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='user_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, default=list), blank=True, default=list, size=None),
        ),
    ]
