# Generated by Django 3.2.6 on 2021-08-19 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210818_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user_count',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
