# Generated by Django 3.2.6 on 2021-08-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_portfolio_user_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user_list',
        ),
    ]
