# Generated by Django 3.2.6 on 2021-08-19 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_portfolio_user_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='users_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
