# Generated by Django 3.2.6 on 2021-08-19 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_portfolio_users_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='users_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None), blank=True, default=list, size=None),
        ),
    ]
