# Generated by Django 3.2.6 on 2021-08-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_portfolio_users_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='users_count',
            field=models.IntegerField(default=0),
        ),
    ]
