# Generated by Django 3.2.6 on 2021-08-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_mailings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'verbose_name': 'рассылку', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='mailings',
            name='message',
            field=models.TextField(max_length=4096, verbose_name='Cообщение'),
        ),
    ]
