# Generated by Django 3.2.6 on 2021-08-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20210821_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'портфель', 'verbose_name_plural': 'Портфели'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='videolesson',
            options={'verbose_name': 'видеоурок', 'verbose_name_plural': 'Видеоуроки'},
        ),
        migrations.AlterField(
            model_name='mailings',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.portfolio', verbose_name='Портфель'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='users_count',
            field=models.IntegerField(default=0, verbose_name='Количество подписанных'),
        ),
    ]
