# Generated by Django 3.2.6 on 2021-08-21 11:39

import app.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20210821_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=app.storage.CustomFileSystemStorage, upload_to='uploads/broadcasts/%Y_%m_%d/', verbose_name='Фото')),
                ('message', models.TextField(max_length=4096, verbose_name='Cообщение')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'рассылку',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.DeleteModel(
            name='Mailings',
        ),
    ]
