# Generated by Django 3.2.6 on 2021-08-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20210821_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/broadcasts/%Y_%m_%d/', verbose_name='Фото'),
        ),
    ]
