# Generated by Django 3.2.6 on 2021-08-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20210823_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastToAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4096, verbose_name='Cообщение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/broadcaststoall/%Y_%m_%d/', verbose_name='Фото')),
                ('to_all', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'рассылку для всех',
                'verbose_name_plural': 'Рассылки для всех',
            },
        ),
    ]
