# Generated by Django 3.2.6 on 2021-08-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_broadcasttoall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcasttoall',
            name='to_all',
        ),
    ]
