# Generated by Django 3.2.6 on 2021-08-24 13:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_remove_broadcasttoall_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_id',
            field=models.CharField(default=app.models.get_code, max_length=6, unique=True, verbose_name='Промокод'),
        ),
    ]
