# Generated by Django 3.2.6 on 2021-08-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_remove_broadcast_to_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4096, verbose_name='Cообщение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/broadcaststoall/%Y_%m_%d/', verbose_name='Фото')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
            ],
            options={
                'verbose_name': 'общую рассылку',
                'verbose_name_plural': 'Общие рассылки',
            },
        ),
        migrations.CreateModel(
            name='BroadcastSelective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4096, verbose_name='Cообщение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/broadcasts/%Y_%m_%d/', verbose_name='Фото')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'выборочную рассылку',
                'verbose_name_plural': 'Выборочные рассылки',
            },
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='BroadcastToAll',
        ),
        migrations.DeleteModel(
            name='Broadcast',
        ),
    ]
