# Generated by Django 3.2.6 on 2021-08-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20210825_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/broadcast-all/%Y_%m_%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='broadcastselective',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/broadcast-selective/%Y_%m_%d/', verbose_name='Фото'),
        ),
    ]
