# Generated by Django 3.2.6 on 2021-08-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20210825_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'портфель', 'verbose_name_plural': ' Портфели'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'промокод', 'verbose_name_plural': ' Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': '   Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='videolesson',
            options={'verbose_name': 'видеоурок', 'verbose_name_plural': '  Видеоуроки'},
        ),
    ]
